rule all:
    input:
        '../data/forfires_year.png', '../data/forfires_temp.png', '../data/temp_year.png'
        
rule download_data:
    output:
        '../data/Agrofood_co2_emission.csv'
    shell:
        'wget -O {output} "https://docs.google.com/uc?export=download&id=1Wytf3ryf9EtOwaloms8HEzLG0yjtRqxr"'
        
rule plot_forfires_year:
    input:
        '../data/Agrofood_co2_emission.csv'
    output:
        '../data/forfires_year.png'
    shell:
        'python plot_forfires_year.py {input} {output} "Albania" "Albanian Forest Fires" "Year" "CO2 Emissions"'
        
rule plot_forfires_temp:
    input:
        '../data/Agrofood_co2_emission.csv'
    output:
        '../data/forfires_temp.png'
    shell:
        'python plot_forfires_temp.py {input} {output} "Albania" "Albanian Forest Fires" "Average Temperature" "CO2 Emissions"'
        
rule plot_temp_year:
    input:
        '../data/Agrofood_co2_emission.csv'
    output:
        '../data/temp_year.png'
    shell:
        'python plot_temp_year.py {input} {output} "Albania" "Albanian Temperatures" "Year" "Average Temperature"'