name: unit tests


on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - master
    
jobs:
    run_unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                cd test/unit
                python -m unittest test_my_utils
                
    run_functional_tests:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - run: |
                cd test/func
                bash test_print_fires.sh
                
    run_stylechecks:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
            - uses: actions/checkout@v2
            - uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: swe4s
                  environment-file: environment.yml       
            - run: pycodestyle $(git ls-files "*.py")
        