name: unit tests


on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - master
    
jobs:
    run_unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                cd test/unit
                python -m unittest test_my_utils
                
    run_functional_tests:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - run: |
                cd ../func
                bash test_print_firest.sh
        